baseURL = 'https://shreya-singh77.netlify.app/'  # Netlify domain
languageCode = 'en-us'
title = ''

[params]
  title_background_image = "img/medicalIntro.png"  # Path relative to the static/ folder
  header_image = "img/medicalIntro.png"            # Path relative to the static/ folder

  # Adding KPC Medical College and Hospital details
  medical_college_address = """
  KPC Medical College and Hospital
  1F, Ratul Lane,
  Jadavpur, Near 8B Bus Stand,
  Kolkata – 700032,
  West Bengal, India.
  Phone: +91 33 2417 0100 / 2417 0200
  Website: www.kpcmedicalcollege.com
  """
