[build]
  publish = "public"         # Hugo will output the site to the public folder
  command = "npx hugo"       # Use Hugo from the locally installed `node_modules`

[context.production.environment]
  HUGO_VERSION = "0.139.0"   # Specify the version of Hugo you're using
