[build]
  publish = "public"         # Where the final site will be published
  command = "hugo"           # The build command (hugo generates the static site)

[context.production.environment]
  HUGO_VERSION = "0.140.2"   # Specify Hugo version

[[plugins]]
  package = "@netlify/plugin-hugo"
